apiVersion: v1
entries:
  k2view-agent:
  - apiVersion: v2
    appVersion: 1.17.0
    created: "2024-02-01T18:07:16.3721371+02:00"
    description: A Helm chart for K2view cloud manager site agent
    digest: 6b9d2bd8cb4d320a4175180b06a0a04c5ee2729eed5a8d9388c8108ee0a3c4f5
    name: k2view-agent
    type: application
    urls:
    - k2view-agent-1.1.0.tgz
    version: 1.1.0
generated: "2024-02-01T18:07:16.3713564+02:00"
